### ISSUE TITLE
Footer and open source license of SpotDiff

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/SpotDiffFrontend#100]
1. 需要將 footer 右下角的 [© 地球公民基金會](https://www.cet-taiwan.org/) 改掉。

        改為
        [地球公民基金會](https://www.cet-taiwan.org/)與 [g0v.tw](https://g0v.tw/) 社群共同開發
        
        沒有 all rights reserved 所以不會使用 ©

2. 在 footer 左下角的關於此專案

    Popup 中希望能加入
        1. 大家來找廠全站由使用者辨識產生之資料以 [CC0 公眾領域貢獻宣告](http://creativecommons.tw/cc0) 釋出授權到公眾領域
        2. 點位經緯度來自 XXXXX （附網址），衛星空照圖來源為 XXXXX（附網址）
        3. 設計圖以 CC-BY姓名標示 4.0 International 釋出，標註「農地違章工廠回報系統貢獻者」，原始碼以 MIT 開放授權公開在[GitHub](https://github.com/Disfactory)上。

Note: 
如果覺得設計圖和程式碼的開源條款太煩雜不想列，我們至少一定要列衛星圖資資料來源和 CC0 公眾領域貢獻宣告，設計圖和原始碼的標示，是可以在 about page 找到

**Comment by aelcenganda** [comment]
@deeper747 我需要你幫補衛星影像資料來源

**Comment by dyfu95** [comment]
resolve by  [7e78641](https://github.com/Disfactory/SpotDiffFrontend/commit/7e78641ca4123ac8f488d403585154314db0b88c)

**Comment by aelcenganda** [comment]
Irvin:
  如果你在辨識題目的下面補上授權宣告，這樣應該就可以了吧？

  例如參考 iTaigi 的標示：「 我同意將辨識結果以 [CC0 公眾領域貢獻宣告](http://creativecommons.tw/cc0) 釋出授權到公眾領域。」
  https://itaigi.tw/k/%E7%A4%A6%E5%B7%A5
  
  或者 Common Voice 的標示： 「如果您參與 Common voice，則您也必須如此。您必須同意 Mozilla 得按照 [CC0](https://creativecommons.org/publicdomain/zero/1.0/) 公眾領域貢獻宣告將您所有的貢獻內容（包含文字、錄音、驗證、意見回饋）提供給公眾使用。」
  
  
  如果你最終開放的資料是： 衛星空照圖 vs 人工辨識的結果（是違章工廠 / 非違章工廠）
  我覺得空照圖可能才會有著作權問題？

誠夏：

  1、我剛玩過一輪，很不錯的創意發想；
  2、事實性的指認不能產生著作權，所以個別指認者的協力，不會擁有著作權；
  3、然將事實性指認的成果進行資料庫整理，可以主張編輯著作的地位，所以要不要主張著作權其實在於Disfactory專案及其後的基金會；
  4、若您們也認為不想主張其後資料庫的編輯著作權利，可以學柏克萊人工智慧研究院(The Berkeley Artificial Intelligence Research, BAIR)的作法，發布一個近似BAIR model license的宣告：https://caffe.berkeleyvision.org/model_zoo.html，意思就是他們不主張AI運算過程產出的著作權利，相關資料是可以不受限制被再利用，但原來拿來演算辨識的圖片，他們不會提供，因為那些圖的著作權利不是他們可以掌控的。
  
  BAIR model license
  
  The Caffe models bundled by the BAIR are released for unrestricted use.
  
  These models are trained on data from the ImageNet project and training data includes internet photos that may be subject to copyright.
  
  Our present understanding as researchers is that there is no restriction placed on the open release of these learned model weights, since none of the original images are distributed in whole or in part. To the extent that the interpretation arises that weights are derivative works of the original copyright holder and they assert such a copyright, UC Berkeley makes no representations as to what use is allowed other than to consider our present release in the spirit of fair use in the academic mission of the university to disseminate knowledge and tools as broadly as possible without restriction.
  
  5、或是就像Irvin說的，你直接把辨識成果的資料、資料集或資料庫，採CC0發布，CC0「理論上」是將有著作權利的客體進行著作權拋棄，但．是，現在愈來愈多的實務上，被用在「這僤東西我不會主張著作權利的表態」，意思就是產出的演算或資料，到底受不受著作權保護，釋出者也不確定，但若是受保護，總之我用CC0宣告了，來表達就算有著作權保護，發布者也拋棄掉了，所以大家可以安心拿去用。像紐約大都會藝術博物館(MET)或故宮博物院於「故宮典藏資料檢索系統」提供72dpi以下圖像：https://antiquities.npm.gov.tw/，就採取這個態度。
  
  6、重點是您提供再利用或釋出的是「資料」，不包含「農委會的空照圖」，那就可以解釋不受原空照圖著作權保護範圍的限制。
  
  請理解，CC歷來的態度，就是拿CC的素材，或其他著作權利素材來進行演算或AI學習或人工辨識，最後的資料成果是與原作品的著作權脫勾的：https://creativecommons.org/tag/artificial-intelligence/
  
  因為著作權保護的範圍是著作的表達，並不及於其背後的概念或邏輯，這規定在著作權法10之1條，所以，若您可以確認標示的成果不需要與農委會空照圖再掛勾合併利用，那它在著作權利的歸屬上，是可以主張斷鏈的！
  
  7、至於GA client ID，可以算是間接性個資，也就是說單獨存在無法辨識個人資料，但與其他配合就有機會反推，我想除非很有必要，不然就不要讓第三方接觸到，或是用Hash Table的方式來給，例如把原ID轉為代號，產出另一份轉過代號的列表，給外部的就是轉過的代號列表，這樣就只有原專案的人員能進行逐筆資料真實身份的mapping，會更合宜些。
