### ISSUE TITLE
將fake database架設在heroku上

### ISSUE THREAD

**Issue by DotSea** [Disfactory/SpotDiffFrontend#12]
目的：能夠讓經由netlify deploy出來的網頁，能夠讀取到 SpofDiff-test-api-server 這個repo裡面的fake database，讓前端在還沒有串disfactory的API前，就可以讓使用者測試。

流程：
1. 將testDB.json、package 'json-server' push到 SpofDiff-test-api-server
2. 將SpofDiff-test-api-server 架設在heroku上
3. SpofDiff-test-api-server中新增.env檔，將api網址設為環境變數
4. 上述做完後tag yukaii

**Comment by DotSea** [comment]
@Yukaii 
 我這邊把假的database架在heroku上了，再麻煩你幫忙設定netlify
https://github.com/Disfactory/SpofDiff-test-api-server
另外也想請你幫忙兩件事情：
1. SpofDiff-test-api-server這個repo中，我想要把database這個repo刪掉，並將main改為default repo
2. 我想要將這個SpofDiff-test-api-server的repo與heroku連結在一起，這樣我就不用push兩次（一次push到repo、一次到heroku），我有跟disfactory提出request了，不知道你有沒有權限幫我approve嗎？

**Comment by Yukaii** [comment]
@DotSea Heroku approve 了，再麻煩給我 heroku 網址~~

**Comment by DotSea** [comment]
@Yukaii 抱歉久等了
https://spotdiff-test-api.herokuapp.com/

**Comment by DotSea** [comment]
Done
[GitHub repo](https://github.com/Disfactory/SpofDiff-test-api-server)
[Heroku URL](https://spotdiff-test-api.herokuapp.com/)
當SpofDiff-test-api-server的main  branch更新時，mock database會自動部署
