### ISSUE TITLE
無法向staging.api.spot.disfactory.tw/ 取得資料

### ISSUE THREAD

**Issue by DotSea** [Disfactory/SpotDiffFrontend#42]
**Expected Behavior**
Tell us what should happen
照理說進入頁面時，可以正確載入各個工廠的資料。

**Current Behavior**
Tell us what happens instead of the expected behavior
無法載入資料，畫面會一直停留在「Loading......」的畫面。

**To Reproduce**
進入遊戲頁面 https://disfactory-spotdiff.netlify.app/#/game

**Possible Solution**
Not obligatory, but suggest a fix/reason for the bug.

**Context (Environment)**
How has this issue affected you? What are you trying to accomplish?
Providing context helps us come up with a solution that is most useful in the real world.
除了桌機版的chrome以外，其他瀏覽器都無法載入資料。
其他瀏覽器包含：
- mobile：chrome, safari, firefox, edge
- desktop：safari, firefox, edge

**Additional context**
我嘗試有透過Edge瀏覽器直接進入api url https://staging.api.spot.disfactory.tw/，
結果瀏覽器告訴我憑證已過期，或許跟這個有關？
<img width="617" alt="截圖 2022-02-06 下午3 30 21" src="https://user-images.githubusercontent.com/85677992/152671550-adc051c1-5b22-4402-a185-0b412fc00f8c.png">

**Screenshots**

各個瀏覽器的devtool error message:

- safari
<img width="644" alt="截圖 2022-02-06 下午3 32 46" src="https://user-images.githubusercontent.com/85677992/152671648-dafecbe2-1f5e-4a3c-aaeb-b8213fea9c3a.png">

- firefox
<img width="962" alt="截圖 2022-02-06 下午3 32 55" src="https://user-images.githubusercontent.com/85677992/152671655-8157f500-5605-4898-b611-5e60bbc2f0f9.png">

- edge
<img width="819" alt="截圖 2022-02-06 下午3 33 07" src="https://user-images.githubusercontent.com/85677992/152671658-fdf02eb2-390d-4201-a27e-78ab1fb2ae66.png">

**Desktop (please complete the following information):**
 - OS: MacOS12.1
 - Browser: safari, firefox,edge

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2
 - OS: iOS15.1
 - Browser chrome, safari, firefox,edge

**Comment by ddio** [comment]
憑證失效了（但不知為何 Chrome 沒有被通知到 XD）

最近 Let's encrypt [因為安全性因素，註銷了一批憑證](https://community.letsencrypt.org/t/sec-error-revoked-certificate/170977)，可能跟那個有關？或許重跑 certbot 就可以了？

**Comment by DotSea** [comment]
2/9 update:
經測試後，網站可以取得data並正確顯示衛星雲圖，bug已解決。
