### ISSUE TITLE
前端切版的一些待優化

### ISSUE THREAD

**Issue by wutingy** [Disfactory/SpotDiffFrontend#54]
https://disfactory-spotdiff.netlify.app/#/
https://disfactory-spotdiff.netlify.app/#/tutorial
https://disfactory-spotdiff.netlify.app/#/ending
https://disfactory-spotdiff.netlify.app/#/game

## 教學
第 2, 4 題少了 2017
<img width="422" alt="Screen Shot 2022-02-21 at 9 03 25 AM" src="https://user-images.githubusercontent.com/8353239/154873323-984bf526-3b5b-4d02-b4d5-db019c971dec.png">

少了分隔 icon（題目版有，教學沒放到）（下圖為 figma 的圖）
<img width="518" alt="Screen Shot 2022-02-21 at 9 10 48 AM" src="https://user-images.githubusercontent.com/8353239/154873711-e0df5cd9-36f8-48ff-a46f-9fa7c59e979b.png">

## 電腦版

不論是教學、還是正式題目，header 上方不需要有 border，框框的 `border-top: 0`。

<img width="835" alt="Screen Shot 2022-02-21 at 9 06 53 AM" src="https://user-images.githubusercontent.com/8353239/154873437-eb115b9f-7d30-4b1b-b8c0-ff4f1a2a57b5.png">

少了 2017
<img width="429" alt="Screen Shot 2022-02-21 at 9 08 44 AM" src="https://user-images.githubusercontent.com/8353239/154873542-c9bebe38-8476-40c3-bfa6-ac944dcb32ef.png">

## 確認送出？
這邊應該要跟 ending 一樣有藍色框框。
![Screen Shot 2022-02-21 at 9 14 58 AM](https://user-images.githubusercontent.com/8353239/154874060-45eb8830-7f43-4bcf-a159-936da98cd960.png)

![Screen Shot 2022-02-21 at 9 14 19 AM](https://user-images.githubusercontent.com/8353239/154874055-df9cc561-5205-498d-88d7-bca6f7455de4.png)

**Comment by wutingy** [comment]
<img width="864" alt="Screen Shot 2022-02-21 at 9 21 48 AM" src="https://user-images.githubusercontent.com/8353239/154874333-9a5b04de-5067-4c36-b4e3-0d6b2e94b59c.png">

**Comment by wutingy** [comment]
Modal 出現的速度有點慢，可以參考：[Basic Dialog](https://mui.com/components/dialogs/)
Basic dialog > open small dialog
感覺大概 0.3-0.5s
<img width="544" alt="Screen Shot 2022-02-21 at 9 26 12 AM" src="https://user-images.githubusercontent.com/8353239/154874740-24b560d2-6b53-4ff8-9d46-a6f37e7d86ab.png">

**Comment by wutingy** [comment]
ending, 確認送出的藍色框框，可以像 intro 一樣，電腦版、手機版共用
<img width="383" alt="Screen Shot 2022-02-21 at 9 31 43 AM" src="https://user-images.githubusercontent.com/8353239/154874892-d890778b-cfac-405a-a70f-46d472615ecc.png">

**Comment by DotSea** [comment]
done by https://github.com/Disfactory/SpotDiffFrontend/pull/55

**Comment by wutingy** [comment]
👏
