### ISSUE TITLE
設計分享圖片

### ISSUE THREAD

**Issue by wutingy** [Disfactory/SpotDiffFrontend#79]
[Figma](https://www.figma.com/file/TVAEC28E3ojabGHc8BawbI/%E5%A4%A7%E5%AE%B6%E4%BE%86%E6%89%BE%E5%BB%A0?node-id=599%3A433)

需要設計 1. 地公分享的圖片（og:image 與此相同）  2. user 從網站分享出去的圖片

**Comment by wutingy** [comment]
![Frame 1](https://user-images.githubusercontent.com/8353239/162678830-f28f8b7b-af5a-4f91-a202-826d84cf32b5.jpg)
![Frame 2](https://user-images.githubusercontent.com/8353239/162678845-5b05b1b2-2142-422c-9c5a-a74661058ffc.jpg)
![地公-share](https://user-images.githubusercontent.com/8353239/162678850-95fc01ab-463a-4ae0-8cb8-79be33d3ea13.jpg)

**Comment by deeper747** [comment]
使用者分享的圖
- 以正義感來號召
- 北港回收廠圖片
![78431734_738322919912550_8280587545281036288_n拷貝](https://user-images.githubusercontent.com/60970217/163188719-79e7f0e3-4159-41d4-aa78-d3fd8d9c24a9.png)

地球公民分享的圖
- 「阿伯出事了」

**Comment by wutingy** [comment]
1. pending
2. 動動手指，拆除違章工廠
（大家來找廠 logo）

**Comment by wutingy** [comment]
<img width="713" alt="Screen Shot 2022-04-20 at 7 45 28 PM" src="https://user-images.githubusercontent.com/8353239/164357258-91cb2cc2-abe6-41ed-bca0-36383417281f.png">
