### ISSUE TITLE
新增 Cookie 和隱私權條款

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/SpotDiffFrontend#8]
1. 可能會需要設計出同意收集 cookie 的文字。小小的放在進入頁面，例如：`點擊按鈕繼續代表同意 cookie 收集與隱私權條款`
2. 要做一個頁面放隱私權條款。我再檢查一下，是否可以直接沿用 Disfactory.tw 主站的

**Comment by aelcenganda** [comment]
Disfactory.tw 的隱私權條款
https://license.disfactory.tw/#%E9%9A%B1%E7%A7%81%E6%AC%8A%E6%A2%9D%E6%AC%BE

Disfactory.tw 的貢獻條款
https://license.disfactory.tw/#%E8%BE%B2%E5%9C%B0%E9%81%95%E7%AB%A0%E5%B7%A5%E5%BB%A0%E5%9B%9E%E5%A0%B1%E7%B3%BB%E7%B5%B1%EF%BC%88disfactory%EF%BC%89%E8%B2%A2%E7%8D%BB%E5%8D%94%E8%AD%B0

**Comment by aelcenganda** [comment]
希望 SpotDiff 的貢獻授權條款，可以新開一個網址放在
https://license.spot.disfactory.tw/

**Comment by aelcenganda** [comment]
最後更新時間： 2022 年 4 月 29 日 19:00 UTC+8

# 大家來找廠（Disfactory-SpotDiff）貢獻協議

感謝您有意願貢獻資料及相關內容（以下統稱「內容」）至大家來找廠（Disfactory-SpotDiff，以下簡稱「本網站」）。此貢獻協議（「協議」）存在於您及本網站管理機關地球公民基金會（「管理者」）間，目的在釐清雙方相關智慧財產權利狀態及其他權利義務關係。請閱讀以下條款及條件並確認，當您回報或上傳內容至本網站時，即表示您接受本協議內容。

1. 貢獻內容之合法及適當狀態
- 您的資料貢獻不應侵害他人之智慧財產權利。如您貢獻內容，代表就您所知您表示，您有權授權管理者及本網站的使用者，依管理者指定、揀選的授權條款，來使用並散布這些內容。
- 請注意管理者並不必然需要將您貢獻的內容包括於本網站上，並且得以在任何時候，將您的貢獻於本網站移除。對您貢獻的內容，管理者並無負擔保管責任。

2. 授與權利

- 您在此授與管理者全球性、免授權金、非專屬、永久、不可撤回之著作權及其他司法管轄區域可能定義之鄰接權及資料庫權之權利，讓其能夠不受前述權利限制使用內容之任何內含物，無論是就原始載體，或採其他型態進行利用。所授與的權利明示包括商業性使用，並且不排除任何領域內的利用。此一授權包括並不限於，將作品進行後續再授權利用，並允許多階的被授權人皆得採再授權方式再作利用。就現行法及著作權契約可容許的最大範圍內，您對管理者或經其授權利用內容之人，亦拋棄或不主張任何著作人格權。
- 除本處訂明之範圍，您所貢獻內容之所有權利、地位，及利益，仍保留在您。

3. 免責聲明
-  在現行法容許的範圍內，您是以現狀及現有之基礎提供本內容，但應保證該內容無侵權之虞。
-  除依法不得事先排除或限縮之責任外，您或管理者皆不應依此協議，為其他歸責理論導致任何損害賠償。

4. 其他事項
- 您所提送之表單及因之所需之註冊、登入程序裡，產生或由您填註的個人資訊，您在此同意管理者後續蒐集、處理及利用該個人資料。
- 本「協議」依據中華民國法律。當本協議任一條款被視為無效時不影響其他部份之有效性。


# 隱私權條款

## 適用範圍

本處所述隱私權政策，適用於您在 spot.disfactory.tw 網站（以下簡稱「本網站」）活動時，所涉及有關個人資料的蒐集、處理及利用。此隱私權條款（「條款」）存在於您及本網站管理機關地球公民基金會（「管理者」）間。請閱讀以下條款及條件並確認，當您持續使用本網站服務，即視為當事人明示同意下述之資料蒐集、處理，及利用方式。

本網站得將您貢獻之內容推送至其他平台，如臉書、Instagram 等社群網路平台，於推送後就該平台之個人資料使用事宜，後續悉由該平台依其隱私權政策進行處理。

## 本網站蒐集使用者資料

使用者自主填註的各項個人識別資料，僅作為認證、授權標示，與相關通知、聯繫用。若使用者未自設資訊屏蔽機制，本網站部分功能會蒐集您的連線設備 IP 位址、使用時間、使用的瀏覽器、瀏覽及點選資料記錄等相關資訊，此記錄為內部應用，絕不對外公佈。 為了提供您最佳的服務，本網站會在您的電腦中放置並取用我們的 Cookie，若您不願接受 Cookie 的寫入，您可在您使用的瀏覽器功能項中設定隱私權等級為高，即可拒絕 Cookie 的寫入，但可能會導至網站某些功能無法正常執行 。

## 資料之保護

本網站採用 HTTPS (Hypertext Transfer Protocol Secure) 傳輸安全協定，利用SSL / TLS來加密封包，保護交換資料的隱私與完整性。

## 本網站對相關資料之去識別化與量化處理

使用者同意本網站得以對其回報資料進行合理妥適之去識別化或相關數據量化的處理。 處理後的資料與其個人識別狀態無法產生連結者，便不再屬於個人資料，後續將得以不受回報目的之限制，被進行利用。

## 與第三人共用個人資料之政策

本網站絕不會提供、交換、出租或出售任何您的個人資料給其他個人、團體、私人企業或公務機關，但有法律依據或合約義務者，不在此限。 前項但書之情形包括不限於：

- 經由您書面同意。
- 法律明文規定。
- 為免除您生命、身體、自由或財產上之危險。
- 與公務機關或學術研究機構合作，基於公共利益為統計或學術研究而有必要，且資料經過提供者處理或蒐集著依其揭露方式無從識別特定之當事人。
- 當您在網站的行為，違反服務條款或可能損害或妨礙網站與其他使用者權益或導致任何人遭受損害時，經網站管理單位研析揭露您的個人資料是為了辨識、聯絡或採取法律行動所必要者。
- 有利於您的權益。

## 隱私權保護政策修訂

本網站將不定時修訂本項政策，以符合最新的個人資料與相關法定權利之保護規範。 使用者對本網站服務的繼續使用，視為明示同意更新版本的隱私權政策。

## 回報機制

本網站對於相關資料的收集，已踐履個人資料保護法及其相關法規的基礎要求，並在資料的處理及利用上，透過彙整或去識別化流程，以強化使用者的隱私防護。相關資料在處理之後，亦將進行公文檢舉與公益目的之分享。 若您對於您的個人資料與貢獻之資料有隱私疑慮，請聯絡管理者，使用者若對您相關資料有進行查閱、更正、停止利用，以及刪除的意見，亦可透過網站回報機制進行提報。

**Comment by aelcenganda** [comment]
需要在教學頁面結束，進入正式便是之前那頁，在 `開始辨識` 的按鈕下面加上一行小字
`點擊開始辨識即我同意將辨識結果以[CC0 公眾領域貢獻宣告](http://creativecommons.tw/cc0) 釋出授權到公眾領域`

**Comment by dyfu95** [comment]
resolve by [ac5bb21](https://github.com/Disfactory/SpotDiffFrontend/pull/102/commits/ac5bb21322b2b520c2fea6d3731ca77b86d8ffa5)
