### ISSUE TITLE
False display name of `before` photo as `after`

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/SpotDiffFrontend#80]
**Expected Behavior**
In the first question of a set, the photo is the "before" photo. The tag should be `before` instead `after`

**Current Behavior**
![螢幕快照 2022-04-13 下午6 55 21](https://user-images.githubusercontent.com/9480974/163166095-3dda5af7-1483-4495-b66f-044616cbdb60.png)

**Comment by dyfu95** [comment]
resolved by [e5a0e6f](https://github.com/Disfactory/SpotDiffFrontend/commit/e5a0e6ff377e56a0b6f41c5176a86e4ac5d6d2ef)
