### ISSUE TITLE
Add `不知道` in the second question of `有擴建` 或 `無擴建`

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/SpotDiffFrontend#82]
**Expected Behavior**
Three buttons for answers as other questions with a choice of `不知道`(雖然我覺得文字改成 `不清楚` 會比較好)

**Current Behavior**
Only two choices in the second question of one set:
`有擴建`
`無擴建`

`有建物`
`無建物`

**Suggested solutions**
`有擴建`
`無擴建`
`不清楚`

`有建物`
`無建物`
`不清楚`

**Context (Environment)**
We still need a third option to lift user's cognitive burdens and indicate the ambiguity of that coordinate.

**Screenshots**
![螢幕快照 2022-04-13 下午6 55 21](https://user-images.githubusercontent.com/9480974/163168884-c7efb57f-0653-4b8b-8606-c56f007d7dd3.png)
![螢幕快照 2022-04-13 下午7 16 45](https://user-images.githubusercontent.com/9480974/163168895-e3294dc7-917a-4f31-8eab-c00d79bfb585.png)

**Comment by dyfu95** [comment]
這要請設計出「不清楚」的按鈕圖

**Comment by aelcenganda** [comment]
大家決定先暫時不要有「不知道」，避免一直都收到 `不知道` 的 0
