### ISSUE TITLE
[文案修改]第一題辨認紅色準心，第二題辨認紅色方框範圍

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/SpotDiffFrontend#84]
## 現在的文案
測試站：https://disfactory-spotdiff.netlify.app/#/
「承上，你覺得 after 準心所在的
位置上有建物嗎？」
「承上，你覺得 after 準心所在的
位置上有擴建嗎？」

## 需要修改的方向
拿掉「準心」

**Comment by wutingy** [comment]
「承上，你覺得 after 有擴建嗎？」
「承上，你覺得 after 有建物嗎？」

**Comment by dyfu95** [comment]
update by [03d7c3a](https://github.com/Disfactory/SpotDiffFrontend/commit/03d7c3a9aa370a125902ffb4600a2b253d4a5965)
